// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKrJ8hUdnlL8mi_3YR5dFSNJTNv_48eL8',
    appId: '1:597999073953:android:d8811d5591704ff4d90ee0',
    messagingSenderId: '597999073953',
    projectId: 'cityvoice-66668',
    databaseURL: 'https://cityvoice-66668-default-rtdb.firebaseio.com',
    storageBucket: 'cityvoice-66668.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC38I8FUEOf_CMMyfV9Z1Ue3kR87PeLiCQ',
    appId: '1:597999073953:ios:648fc6ffabf8a7a3d90ee0',
    messagingSenderId: '597999073953',
    projectId: 'cityvoice-66668',
    databaseURL: 'https://cityvoice-66668-default-rtdb.firebaseio.com',
    storageBucket: 'cityvoice-66668.firebasestorage.app',
    iosBundleId: 'com.amit.cityvoice',
  );
}
